### ISSUE TITLE
Blacklist spawning cleanup for rats fails in mobf.lua line 1038

### ISSUE THREAD

**Issue by ulamthelucky** [sapier/mobf_core#6]
This line:

``` lua
if type(mob.spawning.primary_algorithms) == "table" then
```

For the animal_rat  mob.spawning is nill.
I had rats on in an earlier version of mobf, and removed them from loading for a while, but had a ton of rat spawners all over place spamming the log file.  So I re-enabled the mod, then in mobf settings disabled them, and turned on "Delete disabled mobs+spawners"

All good, but no cleanup, then I looked in the code and saw setup to blacklist and delete them in init, so I retstarted the server and it failed on the above line. 

Maybe this bug report goes in mobf_modpack.  Question though, if there is no spawning defined how can the mobf get cleaned up?

I added a quick check for null before that line, so the server would load:

``` lua
if mob.spawning == nil then
      minetest.log(LOGLEVEL_WARNING, "MOBF blacklist cleanup impossible - no spawning table.")
      return
end
```

And in the log I see my warning I added:
2016-08-06 12:38:43: ACTION[Main]: MOD: animal_rat loading ...
2016-08-06 12:38:43: ACTION[Main]:  adding rat
2016-08-06 12:38:43: ACTION[Main]: MOBF Blacklisthandling: animal_rat:rat
2016-08-06 12:38:43: ACTION[Main]: MOBF blacklist cleanup impossible - no spawning table.
2016-08-06 12:38:43: ACTION[Main]: MOD: animal_rat mod             version 0.2.1 loaded

Could use some help, as I don't understand why spawning is nil there.

**Comment by ulamthelucky** [comment]
Update.  My little code change that restored the server startup to functional, seems to be all that I needed.   The cleanup appears to be working after all.

**Comment by sapier** [comment]
true this is a relic of old spawning mechanisms used prior adv_spawning. I added a fix for next version.
